### PR TITLE
Merged changes from old pcre-ocaml

### PR DESCRIPTION
**Pull request by mmottl**
This PR merges numerous fixes and cleanups from the old [PCRE-OCaml](https://github.com/mmottl/pcre-ocaml).

You may want to add yourself as author to copyright notices since the support of PCRE2 is obviously a significant change. I'll leave it to you to make a new release.

### CODE REVIEW

**Comment by mmottl** [comment]
There seems to be a bug. I'll reopen this PR once it is fixed.

**Comment by mmottl** [comment]
The bug has been fixed. The old API was actually correct and needed. The reason why we needed a `subj_start` is to correctly support lookbehind patterns. `subj_start` allows us to have a hard cutoff for matching e.g. delimiters so they can't look behind. The OPAM GitHub CI framework caught the regression on the package `camelsnakekebab`, which luckily had a test suite using PCRE lookbehind patterns.

The actual problem that needed fixing was the indiscriminate adding of `subj_start` to ovector offsets. If an offset is `-1` in the old PCRE (or `PCRE2_UNSET` here), it needs to be translated to an offset of `-1` in OCaml land. Now that this is fixed, the `camelsnakekebab` test suite succeeds, and so does the `full_split` example that sometimes failed to translate to `NoGroup`.

**Comment by Uzume** [comment]
@mmottl: Thank you! I am really glad to see you becoming interested in this. I know you are not really interested in maintaining this but I happy to see your valuable input nonetheless.

This is a welcome update to mmottl/pcre-ocaml#25.

Now if we can just get this moved over to [semgrep/pcre2-ocaml](https://github.com/semgrep/pcre2-ocaml) and get @chetmurthy to let semgrep (via @kopecs) take over the opam package (as per https://github.com/mmottl/pcre-ocaml/issues/25#issuecomment-2544186789), things would be very interesting (or vice versa; it make little sense to maintain multiple repositories for this).

I personally think it would be best to also merge in [mmottl/pcre-ocaml](https://github.com/mmottl/pcre-ocaml) and make all the PCRE opam packages (PCRE1 and PCRE2 bindings) be maintained in a single repository though. I am sure you guys can work out a means to oversee such things together in the true spirit of open source.

There maybe are even better places as per this earlier https://github.com/mmottl/pcre-ocaml/issues/25#issuecomment-1656757195.

**Comment by chetmurthy** [comment]
Markus, let me know when you think this is ready-to-go, and I'll execute a release.

**Comment by mmottl** [comment]
> I personally think it would be best to also merge in [mmottl/pcre-ocaml](https://github.com/mmottl/pcre-ocaml) and make all the PCRE opam packages (PCRE1 and PCRE2 bindings) be maintained in a single repository though. I am sure you guys can work out a means to oversee such things together in the true spirit of open source.

A lot of people might have to change their package dependencies if we merged the packages. Once PCRE2 becomes more widely used, PCRE1 should eventually be marked as obsolete, which also might be easier if it is a separate package.

> There maybe are even better places as per this earlier [mmottl/pcre-ocaml#25 (comment)](https://github.com/mmottl/pcre-ocaml/issues/25#issuecomment-1656757195).

I'd be perfectly fine with moving these packages to the OCaml community. Now that I've cleaned them up and addressed any outstanding issues and PRs, it's not likely that I'll spend much time on future maintenance.

**Comment by mmottl** [comment]
> Markus, let me know when you think this is ready-to-go, and I'll execute a release.

If you are convinced, too, that the fix addresses the issue you had, I'd be fine merging this.

**Comment by chetmurthy** [comment]
@Uzume, @mmottl has it right: eventually the old pcre library will be going away (it's already disappeared from some Debian releases -- which caused a test-failure recently on OPAM-CI) so eventually `pcre-ocaml` will also disappear.  So merging `pcre-ocaml` and `pcre2-ocaml` would be .... problematic.

I think @mmottl has been trying to keep the old `pcre-ocaml` alive as long as possible, but at some point it will be impossible.

Hopefully by then, everybody will be moved off to the new `pcre2-ocaml`.

BTW, I spoke with the person working on semgrep's pcre2-ocaml, and when they're ready to make their code available publicly, I will be helping them with any of the .... mechanics of release that they'd like.  But I don't think they're ready to do that just yet.

**Comment by chetmurthy** [comment]
@mmottl Roger that, merging and will proceed with a release.

**Pull request merged**
